connector:
    name: oro_importexport
    jobs:
        language_translations_export_to_zip:
            title: "Export Language Translations to ZIP"
            type: export
            steps:
                export:
                    title:     export
                    class:     Oro\Bundle\BatchBundle\Step\ItemStep
                    services:
                        reader:    oro_translation.importexport.reader.translations
                        processor: oro_importexport.processor.export_delegate
                        writer:    oro_translation.importexport.writer.translations_yml
                    parameters: ~
                pack_zip_file:
                    title:     export
                    class:     Oro\Bundle\BatchBundle\Step\ItemStep
                    services:
                        reader:    oro_translation.importexport.reader.translations_yml
                        processor: oro_importexport.processor.export_delegate
                        writer:    oro_translation.importexport.writer.translations_zip
                    parameters: ~

        language_translations_import_from_zip:
            title: "Import Language Translations from ZIP"
            type: import
            steps:
                unpack_zip_file:
                    title:     import
                    class:     Oro\Bundle\BatchBundle\Step\ItemStep
                    services:
                        reader:    oro_translation.importexport.reader.translations_zip
                        processor: oro_importexport.processor.import_delegate
                        writer:    oro_translation.importexport.writer.translations_yml
                    parameters: ~
                import:
                    title:     import
                    class:     Oro\Bundle\BatchBundle\Step\ItemStep
                    services:
                        reader:    oro_translation.importexport.reader.translations_yml
                        processor: oro_importexport.processor.import_delegate
                        writer:    oro_translation.importexport.writer.translations
                    parameters: ~
