datagrid:
    oro-translation-language-grid:
        acl_resource: oro_translation_language_index
        source:
            type: orm
            query:
                select:
                    - language.id
                    - language.code
                    - language.enabled
                    - language.createdAt
                    - language.updatedAt
                from:
                    - { table: %oro_translation.entity.language.class%, alias: language }
        columns:
            code:
                label: oro.translation.language.entity_label
                type: twig
                frontend_type: html
                template: OroTranslationBundle:Language:Datagrid/code.html.twig
            enabled:
                label: oro.translation.language.enabled.label
                type: twig
                frontend_type: html
                template: OroTranslationBundle:Language:Datagrid/enabled.html.twig
            translationCompleteness: ~
            translationStatus: ~
            createdAt:
                label: oro.ui.created_at
                frontend_type: datetime
                renderable: false
            updatedAt:
                label: oro.ui.updated_at
                frontend_type: datetime
                renderable: false
        sorters:
            columns:
                enabled:
                    data_name: language.enabled
                createdAt:
                    data_name: language.createdAt
                updatedAt:
                    data_name: language.updatedAt
            default:
                code: %oro_datagrid.extension.orm_sorter.class%::DIRECTION_DESC
        filters:
            columns:
                code:
                    type: choice
                    data_name: language.code
                    options:
                        field_options:
                            choices: "@oro_translation.provider.language->getAvailableLanguages"
                enabled:
                    type: choice
                    data_name: CAST(language.enabled as int)
                    options:
                        field_options:
                            choices:
                                true: oro.translation.language.enabled.label
                                false: oro.translation.language.disabled.label
                createdAt:
                    type:      datetime
                    data_name: language.createdAt
                    enabled:   false
                updatedAt:
                    type:      datetime
                    data_name: language.updatedAt
                    enabled:   false
        properties:
            id: ~
