config:
    shim:
        'translator':
            exports: 'Translator'
    paths:
        'translator': 'bundles/bazingaexposetranslation/js/translator.min.js'
        'oro/translator': 'bundles/orotranslation/js/translator.js'