config:
    shim:
        'translator':
            exports: 'Translator'
    paths:
        'translator': 'bundles/orotranslation/lib/translator.js'
        'oro/translator': 'bundles/orotranslation/js/translator.js'
        'oro/translation/translation/config-action': 'bundles/orotranslation/js/translation/config-action.js'
