parameters:
    translator.class: Oro\Bundle\TranslationBundle\Translation\Translator
    oro_translation.controller.class: Oro\Bundle\TranslationBundle\Controller\Controller
    oro_translation.extractor.php_code_extractor.class: Oro\Bundle\TranslationBundle\Extractor\PhpCodeExtractor

    oro_translation.service_provider.class: Oro\Bundle\TranslationBundle\Provider\TranslationServiceProvider

    oro_translation.adapter.class: Oro\Bundle\TranslationBundle\Provider\CrowdinAdapter

services:
    oro_translation.controller:
        class: %oro_translation.controller.class%
        arguments: [@translator, @templating, OroTranslationBundle:Translation:translation.js.twig, ""]

    oro_translation.extractor.php_code_extractor:
        class: %oro_translation.extractor.php_code_extractor.class%
        arguments: [@service_container]
        tags:
            - { name: translation.extractor, alias: oro_translation_php_extractor }

    oro_translation.service_provider:
        class: %oro_translation.service_provider.class%
        arguments:
            - @oro_translation.uploader.crowdin_adapter

    oro_translation.uploader.crowdin_adapter:
        class: %oro_translation.adapter.class%
        arguments:
            - %oro_translation.api.crowdin.endpoint%
