parameters:
    translator.class: Oro\Bundle\TranslationBundle\Translation\Translator
    oro_translation.controller.class: Oro\Bundle\TranslationBundle\Controller\Controller
    oro_translation.extractor.php_code_extractor.class: Oro\Bundle\TranslationBundle\Extractor\PhpCodeExtractor

    oro_translation.uploader.class: Oro\Bundle\TranslationBundle\Provider\TranslationUploader

    oro_translation.adapter.class: Oro\Bundle\TranslationBundle\Provider\CrowdinAdapter
    oro_translation.api_key: 5f70cfb8c3735597df1c2879505ac05a
    oro_translation.endpoint: http://api.crowdin.net/api

services:
    oro_translation.controller:
        class: %oro_translation.controller.class%
        arguments: [@translator, @templating, OroTranslationBundle:Translation:translation.js.twig, ""]

    oro_translation.extractor.php_code_extractor:
        class: %oro_translation.extractor.php_code_extractor.class%
        arguments: [@service_container]
        tags:
            - { name: translation.extractor, alias: oro_translation_php_extractor }

    oro_translation.uploader:
        class: %oro_translation.uploader.class%
        arguments:
            - @oro_translation.uploader.crowdin_adapter

    oro_translation.uploader.crowdin_adapter:
        class: %oro_translation.adapter.class%
        arguments:
            - %oro_translation.api_key%
            - %oro_translation.endpoint%
