oro_system_configuration:
    tree:
        system_configuration:
            platform:
                children:
                    general_setup:
                        children:
                            localization:
                                children:
                                    language_settings:
                                        children: []
