oro_system_configuration:
    fields:
        oro_translation.available_translations:
            type:  oro_translation_available_translations
            options:
                label: 'Available translations'
                is_parent_scope_available: false

    tree:
        system_configuration:
            platform:
                children:
                    general_setup:
                        children:
                            localization:
                                children:
                                    language_settings:
                                        children:
                                            - oro_translation.available_translations
