datagrids:
    oro-translation-language-grid:
        acl_resource: oro_translation_language_index
        source:
            type: orm
            query:
                select:
                    - language.id
                    - language.code
                    - language.enabled
                    - language.createdAt
                    - language.updatedAt
                    - CONCAT_WS(' ', languageOwner.firstName, languageOwner.lastName) as ownerName
                    - languageOwner.id as owner
                from:
                    - { table: '%oro_translation.entity.language.class%', alias: language }
                join:
                    left:
                        - { join: language.owner, alias: languageOwner }
        inline_editing:
            enable: true
            entity_name: '%oro_translation.entity.language.class%'
        columns:
            code:
                label: oro.translation.language.entity_label
                type: twig
                frontend_type: html
                template: OroTranslationBundle:Language:Datagrid/code.html.twig
            ownerName:
                acl_resource: oro_translation_language_update
                label: oro.translation.language.owner.label
                inline_editing:
                    enable: true
                    editor:
                        view: oroform/js/app/views/editor/related-id-relation-editor-view
                        view_options:
                            value_field_name: owner
                    autocomplete_api_accessor:
                        class: orouser/js/tools/acl-users-search-api-accessor
                        permission_check_entity_name: Oro_Bundle_TranslationBundle_Entity_Language
                        permission: EDIT
                renderable: false
            enabled:
                label: oro.translation.language.enabled.label
                type: twig
                frontend_type: html
                template: OroTranslationBundle:Language:Datagrid/enabled.html.twig
            translationCompleteness: ~
            translationStatus: ~
            createdAt:
                label: oro.ui.created_at
                frontend_type: datetime
                renderable: false
            updatedAt:
                label: oro.ui.updated_at
                frontend_type: datetime
                renderable: false
        sorters:
            columns:
                enabled:
                    data_name: language.enabled
                createdAt:
                    data_name: language.createdAt
                updatedAt:
                    data_name: language.updatedAt
            default:
                code: '%oro_datagrid.extension.orm_sorter.class%::DIRECTION_DESC'
        filters:
            columns:
                code:
                    type: choice
                    data_name: language.code
                    options:
                        field_options:
                            choices: "@oro_translation.provider.language->getAvailableLanguages"
                enabled:
                    type: choice
                    data_name: CAST(language.enabled as int)
                    options:
                        field_options:
                            choices:
                                true: oro.translation.language.status.enabled
                                false: oro.translation.language.status.disabled
                createdAt:
                    type:      datetime
                    data_name: language.createdAt
                    enabled:   false
                updatedAt:
                    type:      datetime
                    data_name: language.updatedAt
                    enabled:   false
        properties:
            id: ~
            owner: ~

    oro-translation-translations-grid:
        acl_resource: oro_translation_translation_index
        source:
            type: orm
            query:
                # aliases `value`, `key` and `domain` is required for filters and building right condition
                select:
                    - translation.id
                    - language.code
                    - translation.value as value
                    - translationKey.key as key
                    - translationKey.domain as domain
                    - (CASE WHEN translation.value IS NULL THEN 0 ELSE 1 END) as status
                from:
                    - { table: '%oro_translation.entity.language.class%', alias: language }
                join:
                    inner:
                        -
                            join: '%oro_translation.entity.translation_key.class%'
                            alias: translationKey
                            conditionType: WITH
                            condition: 1 = 1 # always true (required for DQLBuilder due require conditionType when joining on Entity class)
                    left:
                        -
                            join: '%oro_translation.entity.translation.class%'
                            alias: translation
                            conditionType: WITH
                            condition: 'translation.language = language AND translation.translationKey = translationKey'
        inline_editing:
            enable: true
            entity_name: '%oro_translation.entity.translation.class%'
            acl_resource: oro_translation_language_translate
        columns:
            id:
                label: oro.translation.translation.id.label
                renderable: false
            code:
                label: oro.translation.translation.language.label
                type: twig
                frontend_type: html
                template: OroTranslationBundle:Language:Datagrid/code.html.twig
            status:
                label: oro.translation.translation.status.label
                frontend_type: boolean
            originalValue:
                label: oro.translation.translation.original_value.label
                type: twig
                frontend_type: html
                template: OroTranslationBundle:Translation:Datagrid/originalValue.html.twig
            value:
                label: oro.translation.translation.value.label
                inline_editing:
                    editor:
                        view: orotranslation/js/app/views/editor/text-editor-view
                    save_api_accessor:
                        route: oro_api_update_translation
                        query_parameter_names:
                            - key
                            - locale
                            - domain 
            key:
                label: oro.translation.translation_key.key.label
            domain:
                label: oro.translation.translation_key.domain.label
            context:
                label: oro.translation.translation.context.label
        sorters:
            multiple_sorting: true
            columns:
                code:
                    data_name: language.code
                status:
                    data_name: status
                value:
                    data_name: value
                key:
                    data_name: key
                domain:
                    data_name: domain
            default:
                code: %oro_datagrid.extension.orm_sorter.class%::DIRECTION_ASC                    
        filters:
            columns:
                code:
                    type: choice
                    data_name: language.code
                    options:
                        field_options:
                            choices: "@oro_translation.provider.language->getAvailableLanguages"
                            multiple: true
                status:
                    type: boolean
                    data_name: CAST(status as int)
                value:
                    type: string
                    data_name: value
                key:
                    type: string
                    data_name: key
                domain:
                    type: choice
                    data_name: domain
                    options:
                        field_options:
                            choices: "@oro_translation.manager.translation->getAvailableDomains"
                            multiple: true
        properties:
            id: ~
            context:
                type: callback
                callable: ["@oro_translation.provider.translation_context", "resolveContext"]
                params:
                    - key
            locale:
                data_name: code
