datagrids:
    oro-translation-language-grid:
        acl_resource: oro_translation_language_index
        source:
            type: orm
            query:
                select:
                    - language.id
                    - language.code
                    - language.enabled
                    - language.createdAt
                    - language.updatedAt
                from:
                    - { table: %oro_translation.entity.language.class%, alias: language }
        columns:
            code:
                label: oro.translation.language.entity_label
                type: twig
                frontend_type: html
                template: OroTranslationBundle:Language:Datagrid/code.html.twig
            enabled:
                label: oro.translation.language.enabled.label
                type: twig
                frontend_type: html
                template: OroTranslationBundle:Language:Datagrid/enabled.html.twig
            translationCompleteness: ~
            translationStatus: ~
            createdAt:
                label: oro.ui.created_at
                frontend_type: datetime
                renderable: false
            updatedAt:
                label: oro.ui.updated_at
                frontend_type: datetime
                renderable: false
        sorters:
            columns:
                enabled:
                    data_name: language.enabled
                createdAt:
                    data_name: language.createdAt
                updatedAt:
                    data_name: language.updatedAt
            default:
                code: %oro_datagrid.extension.orm_sorter.class%::DIRECTION_DESC
        filters:
            columns:
                code:
                    type: choice
                    data_name: language.code
                    options:
                        field_options:
                            choices: "@oro_translation.provider.language->getAvailableLanguages"
                enabled:
                    type: choice
                    data_name: CAST(language.enabled as int)
                    options:
                        field_options:
                            choices:
                                true: oro.translation.language.enabled.label
                                false: oro.translation.language.disabled.label
                createdAt:
                    type:      datetime
                    data_name: language.createdAt
                    enabled:   false
                updatedAt:
                    type:      datetime
                    data_name: language.updatedAt
                    enabled:   false
        properties:
            id: ~
    oro-translation-translations-grid:
        acl_resource: oro_translation_translation_index
        source:
            type: orm
            query:
                select:
                    - translation.id
                    - language.code
                    - translation.value
                    - translationKey.key as _key
                    - translationKey.domain as _domain
                    - (CASE WHEN translation.value IS NULL THEN 0 ELSE 1 END) as _status
                from:
                    - { table: '%oro_translation.entity.language.class%', alias: language }
                join:
                    inner:
                        -
                            join: '%oro_translation.entity.translation_key.class%'
                            alias: translationKey
                            conditionType: WITH
                            condition: 1 = 1
                    left:
                        -
                            join: '%oro_translation.entity.translation.class%'
                            alias: translation
                            conditionType: WITH
                            condition: 'translation.language = language AND translation.translationKey = translationKey'
                where:
                    and:
                        - translationKey = translationKey
        columns:
            id:
                label: oro.translation.translation.id.label
                renderable: false
            code:
                label: oro.translation.translation.language.label
                type: twig
                frontend_type: html
                template: OroTranslationBundle:Language:Datagrid/code.html.twig
            _status:
                label: oro.translation.translation.status.label
                type: twig
                frontend_type: html
                template: OroTranslationBundle:Translation:Datagrid/status.html.twig
                renderable: false
            originalValue:
                label: oro.translation.translation.original_value.label
                type: twig
                frontend_type: html
                template: OroTranslationBundle:Translation:Datagrid/originalValue.html.twig
            value:
                label: oro.translation.translation.value.label
            _key:
                label: oro.translation.translation_key.key.label
                renderable: false
            _domain:
                label: oro.translation.translation_key.domain.label
                renderable: false
        sorters:
            multiple_sorting: true
            columns:
                code:
                    data_name: language.code
                _status:
                    data_name: _status
                value:
                    data_name: translation.value
                _key:
                    data_name: _key
                _domain:
                    data_name: _domain
            default:
                code: %oro_datagrid.extension.orm_sorter.class%::DIRECTION_DESC
        filters:
            columns:
                code:
                    type: choice
                    data_name: language.code
                    options:
                        field_options:
                            choices: "@oro_translation.provider.language->getAvailableLanguages"
                _status:
                    type: choice
                    data_name: CAST(_status as int)
                    options:
                        field_options:
                            choices:
                                true: 'oro.translation.translation.status.translated'
                                false: 'oro.translation.translation.status.untranslated'
                value:
                    type: string
                    data_name: translation.value
                _key:
                    type: string
                    enabled: false
                    data_name: _key
                _domain:
                    type: choice
                    data_name: _domain
                    enabled: false
                    options:
                        field_options:
                            choices: "@oro_translation.manager.translation->getAvailableDomains"
        properties:
            id: ~

