datagrids:
    oro-translation-language-grid:
        acl_resource: oro_translation_language_index
        source:
            type: orm
            query:
                select:
                    - language.id
                    - language.code
                    - language.enabled
                    - language.createdAt
                    - language.updatedAt
                from:
                    - { table: %oro_translation.entity.language.class%, alias: language }
        columns:
            code:
                label: oro.translation.language.entity_label
                type: twig
                frontend_type: html
                template: OroTranslationBundle:Language:Datagrid/code.html.twig
            enabled:
                label: oro.translation.language.enabled.label
                type: twig
                frontend_type: html
                template: OroTranslationBundle:Language:Datagrid/enabled.html.twig
            translationCompleteness: ~
            translationStatus: ~
            createdAt:
                label: oro.ui.created_at
                frontend_type: datetime
                renderable: false
            updatedAt:
                label: oro.ui.updated_at
                frontend_type: datetime
                renderable: false
        sorters:
            columns:
                enabled:
                    data_name: language.enabled
                createdAt:
                    data_name: language.createdAt
                updatedAt:
                    data_name: language.updatedAt
            default:
                code: %oro_datagrid.extension.orm_sorter.class%::DIRECTION_DESC
        filters:
            columns:
                code:
                    type: choice
                    data_name: language.code
                    options:
                        field_options:
                            choices: "@oro_translation.provider.language->getAvailableLanguages"
                enabled:
                    type: choice
                    data_name: CAST(language.enabled as int)
                    options:
                        field_options:
                            choices:
                                true: oro.translation.language.enabled.label
                                false: oro.translation.language.disabled.label
                createdAt:
                    type:      datetime
                    data_name: language.createdAt
                    enabled:   false
                updatedAt:
                    type:      datetime
                    data_name: language.updatedAt
                    enabled:   false
        properties:
            id: ~
    oro-translation-translations-grid:
        acl_resource: oro_translation_translation_index
        source:
            type: orm
            query:
                select:
                    - translation.id
                    - language.code
                    - translation.value
                    - translationKey.key
                    - translationKey.domain
                from:
                    - { table: %oro_translation.entity.translation.class%, alias: translation }
                join:
                    inner:
                        - { join: translation.language, alias: language }
                    left:
                        - { join: translation.translationKey, alias: translationKey }
        columns:
            code:
                label: oro.translation.translation.language.label
                type: twig
                frontend_type: html
                template: OroTranslationBundle:Language:Datagrid/code.html.twig
            originalValue:
                label: oro.translation.translation.original_value.label
                type: twig
                frontend_type: html
                template: OroTranslationBundle:Translation:Datagrid/originalValue.html.twig
            value: ~
            key: ~
            domain: ~
        sorters:
            columns:
                key:
                    data_name: translationKey.key
                domain:
                    data_name: translationKey.domain
                value:
                    data_name: translation.value
            default:
                code: %oro_datagrid.extension.orm_sorter.class%::DIRECTION_DESC
        filters:
            columns:
                code:
                    type: choice
                    data_name: language.code
                    options:
                        field_options:
                            choices: "@oro_translation.provider.language->getAvailableLanguages"
#                domain: ~
#                key: ~
        properties:
            id: ~

